-- AetherV2 Cloud Configs client.
-- Cloud management is intentionally simple: Local/Cloud, select a config, then Save/Share.
-- Share codes are always generated by the server. Owners never type or choose their own code.

local mainapi, license = ...
if type(mainapi) ~= 'table' then return end
license = type(license) == 'table' and license or {}

local profiles = mainapi.Categories and mainapi.Categories.Profiles
local internals = mainapi.CloudConfigInternals
if not profiles or type(internals) ~= 'table' or type(internals.ImportJson) ~= 'function' or type(internals.ConfigPath) ~= 'function' then
	warn('[AetherV2/CloudConfigs] Local config helpers are unavailable')
	return
end

local httpService = game:GetService('HttpService')
local SHADOW_PROFILE = '__cloud_active'
local STATE_PATH = 'aetherv2/profiles/cloud-configs.json'
local AUTOSAVE_IDLE = 120
local PERIODIC_SAVE = 300
local COPY_SYNC_INTERVAL = 300
local SHARE_PATTERN = '^[A-Z2-9][A-Z2-9][A-Z2-9][A-Z2-9]%-[A-Z2-9][A-Z2-9][A-Z2-9][A-Z2-9]$'

local requestFunction = request or http_request
if type(requestFunction) ~= 'function' and type(syn) == 'table' then requestFunction = syn.request end
if type(requestFunction) ~= 'function' and type(http) == 'table' then requestFunction = http.request end

local function endpoint()
	local value = license.PremiumEndpoint
	if (type(value) ~= 'string' or value == '') and getgenv then
		pcall(function() value = getgenv().AetherV2PremiumEndpoint end)
	end
	if type(value) ~= 'string' or value == '' then value = shared.AetherV2PremiumEndpoint end
	if type(value) ~= 'string' or value == '' then value = 'https://aetherv2.onrender.com' end
	return value:gsub('/+$', '')
end

local function notify(text, alert)
	pcall(function()
		mainapi:CreateNotification('Cloud Configs', tostring(text), alert and 8 or 5, alert and 'alert' or 'info')
	end)
end

local function friendlyError(message, status)
	message = tostring(message or 'Cloud request failed')
	local lower = message:lower()
	if status == 401 or status == 403 or lower:find('session', 1, true) or lower:find('premium', 1, true) then
		return 'Your Premium session is no longer valid. Re-execute Aether with a valid Premium key'
	end
	if status == 404 or lower:find('not found', 1, true) then
		return 'That cloud config or share code no longer exists'
	end
	if status == 409 or lower:find('conflict', 1, true) then
		return 'Cloud Configs changed remotely. Try the action again'
	end
	if status == 429 then return 'Cloud Configs is being used too quickly. Try again shortly' end
	if status and status >= 500 then return 'Cloud Configs is temporarily unavailable on the server' end
	if lower:find('http request', 1, true) or lower:find('executor', 1, true) then
		return 'Your executor does not support the HTTP request needed for Cloud Configs'
	end
	return message
end

local function ensureStateFolder()
	if makefolder and (not isfolder or not isfolder('aetherv2')) then pcall(makefolder, 'aetherv2') end
	if makefolder and (not isfolder or not isfolder('aetherv2/profiles')) then pcall(makefolder, 'aetherv2/profiles') end
end

local function loadState()
	local result = {mode = 'Local', autoSave = true, activeCloudId = nil, selectedCloudId = nil, localSync = {}}
	if not isfile or not isfile(STATE_PATH) then return result end
	local ok, decoded = pcall(function() return httpService:JSONDecode(readfile(STATE_PATH)) end)
	if not ok or type(decoded) ~= 'table' then return result end
	if decoded.mode == 'Cloud' then result.mode = 'Cloud' end
	if decoded.autoSave ~= nil then result.autoSave = decoded.autoSave == true end
	result.activeCloudId = type(decoded.activeCloudId) == 'string' and decoded.activeCloudId or nil
	result.selectedCloudId = type(decoded.selectedCloudId) == 'string' and decoded.selectedCloudId or nil
	result.localSync = type(decoded.localSync) == 'table' and decoded.localSync or {}
	return result
end

local state = loadState()
local isPremium = shared.AetherV2PremiumAuthorized == true
	and type(shared.AetherV2PremiumToken) == 'string'
	and shared.AetherV2PremiumToken ~= ''
if not isPremium then state.mode = 'Local' end

local function saveState()
	ensureStateFolder()
	pcall(writefile, STATE_PATH, httpService:JSONEncode(state))
end

local function urlEncode(value)
	local ok, encoded = pcall(httpService.UrlEncode, httpService, tostring(value))
	return ok and encoded or tostring(value)
end

local function decode(body)
	if type(body) ~= 'string' or body == '' then return nil end
	local ok, value = pcall(httpService.JSONDecode, httpService, body)
	return ok and value or nil
end

local function cloudRequest(method, path, body, premiumRequired)
	method = string.upper(method or 'GET')
	if premiumRequired then
		if not isPremium then return nil, 'AetherV2 Premium is required for Cloud management', 403 end
		local separator = path:find('?', 1, true) and '&' or '?'
		path ..= separator..'session='..urlEncode(shared.AetherV2PremiumToken)
	end

	local url = endpoint()..path
	local status, responseBody
	if type(requestFunction) == 'function' then
		local requestData = {Url = url, Method = method, Headers = {['Content-Type'] = 'application/json'}}
		if body ~= nil then requestData.Body = httpService:JSONEncode(body) end
		local ok, response = pcall(requestFunction, requestData)
		if not ok then return nil, friendlyError(response), 0 end
		if type(response) ~= 'table' then return nil, 'Cloud Configs received an invalid HTTP response', 0 end
		status = tonumber(response.StatusCode or response.Status or response.status_code or 200) or 0
		responseBody = response.Body or response.body or ''
	else
		if method ~= 'GET' then return nil, friendlyError('executor HTTP request support is unavailable'), 0 end
		local ok, value = pcall(game.HttpGet, game, url, true)
		if not ok then return nil, friendlyError(value), 0 end
		status, responseBody = 200, value
	end

	local parsed = decode(responseBody)
	if status < 200 or status >= 300 then
		local raw = type(parsed) == 'table' and parsed.error or ('HTTP '..tostring(status))
		return nil, friendlyError(raw, status), status
	end
	if type(parsed) ~= 'table' then return nil, 'Cloud Configs returned invalid data', status end
	if parsed.success == false then return nil, friendlyError(parsed.error, status), status end
	return parsed, nil, status
end

local originalSave = mainapi.Save
local originalUninject = mainapi.Uninject
local running = true
local suppressDirty = false
local dirty = false
local lastObservedPayload
local lastChangedAt = os.clock()
local lastUploadedAt = os.clock()
local mode = isPremium and state.mode or 'Local'
local activeCloudId = isPremium and state.activeCloudId or nil
local selectedCloudId = isPremium and state.selectedCloudId or nil
local cloudConfigs, cloudById, cloudRows = {}, {}, {}
local refreshCloudControls, refreshCloudRows, applyMode, refreshLocalSyncToggle
local applyingSyncToggle, applyingLocalSyncToggle = false, false

local function serializeCurrent(saveFirst)
	if saveFirst and type(originalSave) == 'function' then
		local ok, err = pcall(originalSave, mainapi)
		if not ok then return nil, tostring(err) end
	end
	local path = internals.ConfigPath(mainapi.Profile)
	if not isfile or not isfile(path) then return nil, 'Save the current local config once before uploading it' end
	local ok, configText = pcall(readfile, path)
	if not ok or type(configText) ~= 'string' or configText == '' then return nil, 'The current config could not be read' end
	local wrapper = {config = configText}
	local guiPath = 'aetherv2/profiles/'..game.GameId..'.gui.txt'
	if isfile(guiPath) then
		local guiOk, guiText = pcall(readfile, guiPath)
		if guiOk and type(guiText) == 'string' and guiText ~= '' then wrapper.gui = guiText end
	end
	local encodedOk, encoded = pcall(httpService.JSONEncode, httpService, wrapper)
	return encodedOk and encoded or nil, encodedOk and nil or tostring(encoded)
end

local function selectedConfig()
	return selectedCloudId and cloudById[selectedCloudId] or nil
end

local function formatSaved(value)
	if type(value) ~= 'string' or value == '' then return 'Never' end
	return value:gsub('T', ' '):gsub('%.%d+Z$', ' UTC'):gsub('Z$', ' UTC'):sub(1, 23)
end

local function normalizedShareCode(value)
	local code = tostring(value or ''):upper():gsub('%s+', '')
	if code == '' then return nil, 'Paste a share code first, for example ABCD-2345' end
	if not code:match(SHARE_PATTERN) then return nil, 'Share codes look like ABCD-2345' end
	return code
end

local function resolveShare(rawCode)
	local code, validation = normalizedShareCode(rawCode)
	if not code then return nil, validation end
	local response, err, status = cloudRequest('GET', '/cloud/share/'..urlEncode(code), nil, false)
	if not response then
		if status == 404 then return nil, 'That share code is invalid, disabled, or was regenerated' end
		return nil, err
	end
	local config = response.config
	if type(config) ~= 'table' or type(config.payload) ~= 'string' then return nil, 'That share code returned invalid config data' end
	if tostring(config.placeId) ~= tostring(mainapi.Place) then return nil, 'That share code is for a different game' end
	return config, nil, code
end

local function uniqueLocalName(base)
	base = tostring(base or 'Shared Config'):gsub('^%s*(.-)%s*$', '%1')
	if base == '' then base = 'Shared Config' end
	local used = {}
	for _, profile in mainapi.Profiles or {} do
		if type(profile) == 'table' and type(profile.Name) == 'string' then used[profile.Name:lower()] = true end
	end
	if not used[base:lower()] then return base end
	for index = 2, 99 do
		local candidate = base..' '..index
		if not used[candidate:lower()] then return candidate end
	end
	return base..' Copy'
end

local function localSyncKey(profile)
	return tostring(mainapi.Place)..':'..tostring(profile)
end

local function importLocalShare(code, requestedName, syncEnabled)
	local config, err, normalized = resolveShare(code)
	if not config then return false, err end
	local wanted = tostring(requestedName or ''):gsub('^%s*(.-)%s*$', '%1')
	local name = uniqueLocalName(wanted ~= '' and wanted or ((config.name or 'Shared Config')..' Copy'))
	suppressDirty = true
	local ok, result = internals.ImportJson(config.payload, name, false)
	suppressDirty = false
	if not ok then return false, result end
	if syncEnabled then
		state.localSync[localSyncKey(result)] = {
			profile = result,
			placeId = tostring(mainapi.Place),
			code = normalized,
			lastSaved = config.lastSaved,
			enabled = true
		}
	end
	saveState()
	return true, result
end

local function syncLocalCopy(key, record)
	if not running or type(record) ~= 'table' or record.enabled ~= true then return end
	local config, err = resolveShare(record.code)
	if not config then
		record.enabled = false
		record.invalidated = true
		saveState()
		if mainapi.Profile == record.profile then notify('Sync stopped: '..tostring(err), true) end
		return
	end
	if config.lastSaved == record.lastSaved then return end
	suppressDirty = true
	local ok, result = internals.ImportJson(config.payload, record.profile, true)
	if ok and mainapi.Profile == record.profile then
		pcall(mainapi.Load, mainapi, true, record.profile)
		pcall(originalSave, mainapi, record.profile)
	end
	suppressDirty = false
	if ok then
		record.lastSaved = config.lastSaved
		record.invalidated = nil
		saveState()
	else
		warn('[AetherV2/CloudConfigs] Copy sync failed: '..tostring(result))
	end
end

local function fetchCloudConfig(id)
	local response, err = cloudRequest('GET', '/cloud/configs/'..urlEncode(id), nil, true)
	return response and response.config or nil, err
end

local function loadCloudConfig(id, quiet)
	local config, err = fetchCloudConfig(id)
	if not config then if not quiet then notify(err, true) end return false end
	suppressDirty = true
	local ok, result = internals.ImportJson(config.payload, SHADOW_PROFILE, false)
	suppressDirty = false
	if not ok then if not quiet then notify(result, true) end return false end
	activeCloudId, selectedCloudId = id, id
	state.activeCloudId, state.selectedCloudId, state.mode = id, id, 'Cloud'
	mode, dirty = 'Cloud', false
	lastObservedPayload = serializeCurrent(false)
	lastChangedAt, lastUploadedAt = os.clock(), os.clock()
	cloudById[id] = config
	saveState()
	if applyMode then applyMode() end
	if refreshCloudControls then refreshCloudControls() end
	if not quiet then notify('Loaded '..tostring(config.name or 'cloud config')) end
	return true
end

local function saveCloudConfig(id, quiet)
	if not running or not isPremium or not id then return false end
	local payload, payloadErr = serializeCurrent(true)
	if not payload then if not quiet then notify(payloadErr, true) end return false end
	local response, err = cloudRequest('PUT', '/cloud/configs/'..urlEncode(id), {payload = payload, placeId = tostring(mainapi.Place)}, true)
	if not response then if not quiet then notify(err, true) end return false end
	if type(response.config) == 'table' then cloudById[id] = response.config end
	dirty = false
	lastObservedPayload, lastUploadedAt = payload, os.clock()
	if refreshCloudControls then refreshCloudControls() end
	if not quiet then notify('Saved to Cloud') end
	return true
end

local function flushAutosave(force)
	if not running and not force then return false end
	if not isPremium or not state.autoSave or not activeCloudId or mainapi.Profile ~= SHADOW_PROFILE then return false end
	local payload = serializeCurrent(force == true)
	if type(payload) == 'string' and payload ~= lastObservedPayload then
		lastObservedPayload, dirty, lastChangedAt = payload, true, os.clock()
	end
	if not dirty then return false end
	local now = os.clock()
	if not force and now - lastChangedAt < AUTOSAVE_IDLE and now - lastUploadedAt < PERIODIC_SAVE then return false end
	return saveCloudConfig(activeCloudId, true)
end

local localControlObjects = {}
for _, option in profiles.Options or {} do
	if type(option) == 'table' and typeof(option.Object) == 'Instance' then table.insert(localControlObjects, option.Object) end
end

local window = profiles.Object
local children = window and window:FindFirstChild('Children')
local localAdd = children and children:FindFirstChild('Add')
local repoButton = window and window:FindFirstChild('PresetDownload', true)
local headerTitle = window and window:FindFirstChild('Title')
local cloudControlObjects, sharedControlObjects = {}, {}

local function remember(control, list)
	if type(control) == 'table' and typeof(control.Object) == 'Instance' then table.insert(list, control.Object) end
	return control
end

local function setButtonText(control, text)
	if not control or typeof(control.Object) ~= 'Instance' then return end
	if control.Object:IsA('TextButton') then control.Object.Text = tostring(text) return end
	local title = control.Object:FindFirstChild('Title', true)
	if title and title:IsA('TextLabel') then title.Text = tostring(text) end
end

local modeButton
if isPremium and window and headerTitle then
	modeButton = Instance.new('TextButton')
	modeButton.Name = 'CloudMode'
	modeButton.Size = UDim2.fromOffset(52, 20)
	modeButton.Position = UDim2.new(1, -134, 0, 11)
	modeButton.BackgroundTransparency = 1
	modeButton.Text = mode:upper()
	modeButton.TextColor3 = headerTitle.TextColor3
	modeButton.TextSize = 10
	modeButton.FontFace = headerTitle.FontFace
	modeButton.Parent = window
end

local cloudAdd, cloudAddText
if isPremium and localAdd then
	cloudAdd = localAdd:Clone()
	cloudAdd.Name = 'CloudAdd'
	cloudAdd.Visible = false
	cloudAdd.Parent = localAdd.Parent
	cloudAddText = cloudAdd:FindFirstChildWhichIsA('TextBox', true)
	if cloudAddText then
		cloudAddText.Text = ''
		cloudAddText.PlaceholderText = 'Name (optional)'
	end
end

local lastSavedButton, saveNowButton, autoSaveToggle, renameBox, renameButton, deleteButton
local restoreButton, shareStatusButton, generateShareButton, copyShareButton, regenerateShareButton, disableShareButton, cloudSyncToggle

if isPremium then
	lastSavedButton = remember(profiles:CreateButton({Name = 'Last Saved: Never', Function = function() end}), cloudControlObjects)
	saveNowButton = remember(profiles:CreateButton({Name = 'Save to Cloud', Function = function()
		if not selectedCloudId then return notify('Choose a cloud config first', true) end
		task.spawn(saveCloudConfig, selectedCloudId, false)
	end}), cloudControlObjects)
	autoSaveToggle = remember(profiles:CreateToggle({Name = 'Auto Save', Default = state.autoSave, Function = function(enabled)
		state.autoSave = enabled == true
		saveState()
	end, Tooltip = 'Saves changed cloud configs automatically and before self-destruct'}), cloudControlObjects)
	renameBox = remember(profiles:CreateTextBox({Name = 'Rename', Placeholder = 'New name'}), cloudControlObjects)
	renameButton = remember(profiles:CreateButton({Name = 'Rename', Function = function()
		if not selectedCloudId then return notify('Choose a cloud config first', true) end
		local name = tostring(renameBox.Value or ''):gsub('^%s*(.-)%s*$', '%1')
		if name == '' then return notify('Type the new name first', true) end
		task.spawn(function()
			local response, err = cloudRequest('PATCH', '/cloud/configs/'..urlEncode(selectedCloudId), {action = 'rename', name = name}, true)
			if not response then return notify(err, true) end
			renameBox:SetValue('', false)
			notify('Renamed cloud config')
			if refreshCloudRows then refreshCloudRows(true) end
		end)
	end}), cloudControlObjects)
	deleteButton = remember(profiles:CreateButton({Name = 'Delete Cloud Config', Function = function()
		if not selectedCloudId then return notify('Choose a cloud config first', true) end
		local deleting = selectedCloudId
		task.spawn(function()
			local response, err = cloudRequest('DELETE', '/cloud/configs/'..urlEncode(deleting), nil, true)
			if not response then return notify(err, true) end
			if activeCloudId == deleting then activeCloudId, state.activeCloudId, dirty = nil, nil, false end
			selectedCloudId, state.selectedCloudId = nil, nil
			saveState()
			notify('Deleted cloud config')
			if refreshCloudRows then refreshCloudRows(true) end
		end)
	end}), cloudControlObjects)
	restoreButton = remember(profiles:CreateButton({Name = 'Restore Previous Version', Function = function()
		if not selectedCloudId then return notify('Choose a cloud config first', true) end
		local id = selectedCloudId
		task.spawn(function()
			local response, err = cloudRequest('PATCH', '/cloud/configs/'..urlEncode(id), {action = 'restore-backup'}, true)
			if not response then return notify(err, true) end
			loadCloudConfig(id, true)
			notify('Restored the previous cloud version')
			if refreshCloudRows then refreshCloudRows(true) end
		end)
	end}), cloudControlObjects)
	shareStatusButton = remember(profiles:CreateButton({Name = 'Share Code: Not generated', Function = function() end}), cloudControlObjects)
	generateShareButton = remember(profiles:CreateButton({Name = 'Generate Share Code', Function = function()
		if not selectedCloudId then return notify('Choose a cloud config first', true) end
		task.spawn(function()
			local response, err = cloudRequest('PATCH', '/cloud/configs/'..urlEncode(selectedCloudId), {action = 'sharing', mode = 'generate'}, true)
			if not response then return notify(err, true) end
			cloudById[selectedCloudId] = response.config
			refreshCloudControls()
			local code = response.config and response.config.shareCode
			local copy = setclipboard or toclipboard
			if code and type(copy) == 'function' then pcall(copy, code) end
			notify(code and ('Generated and copied '..code) or 'Share code generated')
		end)
	end, Tooltip = 'Aether automatically creates a random share code for this config'}), cloudControlObjects)
	copyShareButton = remember(profiles:CreateButton({Name = 'Copy Share Code', Function = function()
		local config = selectedConfig()
		if not config or not config.shareCode then return notify('Generate a share code first', true) end
		local copy = setclipboard or toclipboard
		if type(copy) ~= 'function' then return notify('Clipboard access is unavailable', true) end
		if pcall(copy, config.shareCode) then notify('Copied '..config.shareCode) else notify('Could not copy the share code', true) end
	end}), cloudControlObjects)
	regenerateShareButton = remember(profiles:CreateButton({Name = 'Regenerate Share Code', Function = function()
		if not selectedCloudId then return notify('Choose a cloud config first', true) end
		task.spawn(function()
			local response, err = cloudRequest('PATCH', '/cloud/configs/'..urlEncode(selectedCloudId), {action = 'sharing', mode = 'regenerate'}, true)
			if not response then return notify(err, true) end
			cloudById[selectedCloudId] = response.config
			refreshCloudControls()
			local code = response.config and response.config.shareCode
			local copy = setclipboard or toclipboard
			if code and type(copy) == 'function' then pcall(copy, code) end
			notify('New code generated; the old code no longer works')
		end)
	end}), cloudControlObjects)
	disableShareButton = remember(profiles:CreateButton({Name = 'Disable Sharing', Function = function()
		if not selectedCloudId then return notify('Choose a cloud config first', true) end
		task.spawn(function()
			local response, err = cloudRequest('PATCH', '/cloud/configs/'..urlEncode(selectedCloudId), {action = 'sharing', mode = 'disable'}, true)
			if not response then return notify(err, true) end
			cloudById[selectedCloudId] = response.config
			refreshCloudControls()
			notify('Sharing disabled; the old code no longer works')
		end)
	end}), cloudControlObjects)
	cloudSyncToggle = remember(profiles:CreateToggle({Name = 'Sync to Original', Function = function(enabled)
		if applyingSyncToggle then return end
		local config = selectedConfig()
		if not config or not config.isCopy then return end
		task.spawn(function()
			local response, err = cloudRequest('PATCH', '/cloud/configs/'..urlEncode(config.id), {action = 'sync', enabled = enabled == true}, true)
			if not response then notify(err, true) return refreshCloudControls() end
			cloudById[config.id] = response.config
			refreshCloudControls()
		end)
	end, Tooltip = 'Keep this imported copy updated from its owner. Your edits never write back'}), cloudControlObjects)
end

local importCodeBox = remember(profiles:CreateTextBox({Name = 'Share Code', Placeholder = 'ABCD-2345'}), sharedControlObjects)
local importNameBox = remember(profiles:CreateTextBox({Name = 'Copy Name', Placeholder = 'Optional'}), sharedControlObjects)
local importSyncToggle = remember(profiles:CreateToggle({Name = 'Keep Copy Synced', Default = false}), sharedControlObjects)
local importButton = remember(profiles:CreateButton({Name = 'Import Share Code', Function = function()
	local code, name, sync = importCodeBox.Value, importNameBox.Value, importSyncToggle.Enabled == true
	task.spawn(function()
		local source, sourceErr, normalized = resolveShare(code)
		if not source then return notify(sourceErr, true) end
		if isPremium and mode == 'Cloud' then
			local response, err = cloudRequest('POST', '/cloud/import', {code = normalized, name = name ~= '' and name or nil, sync = sync}, true)
			if not response then return notify(err, true) end
			selectedCloudId, state.selectedCloudId = response.config.id, response.config.id
			saveState()
			importCodeBox:SetValue('', false)
			importNameBox:SetValue('', false)
			notify('Imported a cloud copy')
			if refreshCloudRows then refreshCloudRows(true) end
		else
			local ok, result = importLocalShare(normalized, name, sync)
			if not ok then return notify(result, true) end
			importCodeBox:SetValue('', false)
			importNameBox:SetValue('', false)
			notify('Imported '..result..' into Local configs')
		end
	end)
end, Tooltip = 'Paste a code someone shared with you. Free users import it as a normal local config'}), sharedControlObjects)

local localSyncToggle = remember(profiles:CreateToggle({Name = 'Keep Current Copy Synced', Function = function(enabled)
	if applyingLocalSyncToggle or mode ~= 'Local' then return end
	local record = state.localSync[localSyncKey(mainapi.Profile)]
	if not record then return end
	record.enabled, record.invalidated = enabled == true, nil
	saveState()
	if enabled then task.spawn(syncLocalCopy, localSyncKey(mainapi.Profile), record) end
end}), sharedControlObjects)

refreshLocalSyncToggle = function()
	if not localSyncToggle or typeof(localSyncToggle.Object) ~= 'Instance' then return end
	local record = mode == 'Local' and state.localSync[localSyncKey(mainapi.Profile)] or nil
	localSyncToggle.Object.Visible = record ~= nil
	if record and localSyncToggle.Enabled ~= (record.enabled == true) then
		applyingLocalSyncToggle = true
		localSyncToggle:Toggle()
		applyingLocalSyncToggle = false
	end
end

refreshCloudControls = function()
	if not isPremium then return end
	local config = selectedConfig()
	setButtonText(lastSavedButton, 'Last Saved: '..formatSaved(config and config.lastSaved))
	setButtonText(shareStatusButton, 'Share Code: '..(config and config.shareCode or 'Not generated'))
	if restoreButton and restoreButton.Object then restoreButton.Object.Visible = mode == 'Cloud' and config ~= nil and config.hasBackup == true end
	if generateShareButton and generateShareButton.Object then generateShareButton.Object.Visible = mode == 'Cloud' and config ~= nil and not config.shareCode end
	if copyShareButton and copyShareButton.Object then copyShareButton.Object.Visible = mode == 'Cloud' and config ~= nil and config.shareCode ~= nil end
	if regenerateShareButton and regenerateShareButton.Object then regenerateShareButton.Object.Visible = mode == 'Cloud' and config ~= nil and config.shareCode ~= nil end
	if disableShareButton and disableShareButton.Object then disableShareButton.Object.Visible = mode == 'Cloud' and config ~= nil and config.shareCode ~= nil end
	if cloudSyncToggle and cloudSyncToggle.Object then
		cloudSyncToggle.Object.Visible = mode == 'Cloud' and config ~= nil and config.isCopy == true
		if config and config.isCopy and cloudSyncToggle.Enabled ~= (config.syncEnabled == true) then
			applyingSyncToggle = true
			cloudSyncToggle:Toggle()
			applyingSyncToggle = false
		end
	end
end

local function findLocalTemplate()
	for _, object in profiles.Objects or {} do
		if typeof(object) == 'Instance' and object.Name ~= SHADOW_PROFILE then return object end
	end
end

local function clearCloudRows()
	for _, row in cloudRows do if row and row.Parent then row:Destroy() end end
	table.clear(cloudRows)
end

local function rebuildCloudRows()
	clearCloudRows()
	if not isPremium or mode ~= 'Cloud' or not children then return end
	local template = findLocalTemplate()
	if not template then return end
	for _, config in cloudConfigs do
		local row = template:Clone()
		row.Name = 'Cloud_'..config.id
		row.Visible = true
		for _, childName in {'Dots', 'Bind', 'Cover'} do
			local child = row:FindFirstChild(childName)
			if child then child:Destroy() end
		end
		local title = row:FindFirstChild('Title')
		if title and title:IsA('TextLabel') then
			title.Text = config.name
			if config.id == activeCloudId then title.TextColor3 = Color3.fromHSV(mainapi.GUIColor.Hue, mainapi.GUIColor.Sat, mainapi.GUIColor.Value) end
		end
		local stroke = row:FindFirstChildOfClass('UIStroke')
		if stroke then stroke.Enabled = config.id == activeCloudId end
		row.Parent = children
		row.MouseEnter:Connect(function() if stroke then stroke.Enabled = true end end)
		row.MouseLeave:Connect(function() if stroke then stroke.Enabled = config.id == activeCloudId end end)
		row.MouseButton1Click:Connect(function()
			selectedCloudId, state.selectedCloudId = config.id, config.id
			saveState()
			refreshCloudControls()
			task.spawn(loadCloudConfig, config.id, false)
		end)
		table.insert(cloudRows, row)
	end
end

local function fetchCloudList()
	if not isPremium or not running then return false end
	local response, err = cloudRequest('GET', '/cloud/configs?placeId='..urlEncode(mainapi.Place), nil, true)
	if not response then notify(err, true) return false end
	cloudConfigs = type(response.configs) == 'table' and response.configs or {}
	cloudById = {}
	for _, config in cloudConfigs do cloudById[config.id] = config end
	if selectedCloudId and not cloudById[selectedCloudId] then selectedCloudId = nil end
	if not selectedCloudId and cloudConfigs[1] then selectedCloudId = cloudConfigs[1].id end
	state.selectedCloudId = selectedCloudId
	if activeCloudId and not cloudById[activeCloudId] then activeCloudId, state.activeCloudId, dirty = nil, nil, false end
	saveState()
	rebuildCloudRows()
	refreshCloudControls()
	return true
end

refreshCloudRows = function(fetchFirst)
	if fetchFirst then return task.spawn(fetchCloudList) end
	rebuildCloudRows()
end

local function automaticCloudName()
	local used = {}
	for _, config in cloudConfigs do used[tostring(config.name):lower()] = true end
	for index = 1, 99 do
		local candidate = index == 1 and 'Cloud Config' or ('Cloud Config '..index)
		if not used[candidate:lower()] then return candidate end
	end
	return 'Cloud Config '..tostring(os.time())
end

local cloudAddButton = cloudAdd and cloudAdd:FindFirstChild('AddButton', true)
local function createCloudFromCurrent()
	if not isPremium or not running then return end
	local name = cloudAddText and cloudAddText.Text:gsub('^%s*(.-)%s*$', '%1') or ''
	if name == '' then name = automaticCloudName() end
	local payload, payloadErr = serializeCurrent(true)
	if not payload then return notify(payloadErr, true) end
	local response, err = cloudRequest('POST', '/cloud/configs', {name = name, placeId = tostring(mainapi.Place), payload = payload}, true)
	if not response then return notify(err, true) end
	if cloudAddText then cloudAddText.Text = '' end
	selectedCloudId, state.selectedCloudId = response.config.id, response.config.id
	saveState()
	notify('Created '..name)
	fetchCloudList()
end
if cloudAddButton then cloudAddButton.MouseButton1Click:Connect(function() task.spawn(createCloudFromCurrent) end) end
if cloudAddText then cloudAddText.FocusLost:Connect(function(enter) if enter then task.spawn(createCloudFromCurrent) end end) end

local originalProfileChangeValue = profiles.ChangeValue
profiles.ChangeValue = function(self, ...)
	local results = table.pack(originalProfileChangeValue(self, ...))
	task.defer(function()
		if not running then return end
		if applyMode then applyMode() end
		if refreshLocalSyncToggle then refreshLocalSyncToggle() end
		if mode == 'Cloud' then rebuildCloudRows() end
	end)
	return table.unpack(results, 1, results.n)
end

applyMode = function()
	if not running then return end
	if not isPremium then mode = 'Local' end
	state.mode = mode
	if headerTitle then headerTitle.Text = mode == 'Cloud' and 'Cloud Configs' or 'Configs' end
	if modeButton then modeButton.Text = mode:upper() end
	for _, object in localControlObjects do if object.Parent then object.Visible = mode == 'Local' end end
	for _, object in cloudControlObjects do if object.Parent then object.Visible = mode == 'Cloud' end end
	for _, object in sharedControlObjects do if object.Parent then object.Visible = true end end
	for _, object in profiles.Objects or {} do if typeof(object) == 'Instance' then object.Visible = mode == 'Local' and object.Name ~= SHADOW_PROFILE end end
	if localAdd then localAdd.Visible = mode == 'Local' end
	if repoButton then repoButton.Visible = mode == 'Local' end
	if cloudAdd then cloudAdd.Visible = mode == 'Cloud' end
	if mode == 'Cloud' then rebuildCloudRows() else clearCloudRows() end
	refreshCloudControls()
	refreshLocalSyncToggle()
	saveState()
end

if modeButton then
	modeButton.MouseButton1Click:Connect(function()
		mode = mode == 'Local' and 'Cloud' or 'Local'
		applyMode()
		if mode == 'Cloud' then task.spawn(fetchCloudList) end
	end)
end

mainapi.Save = function(self, ...)
	local results = table.pack(originalSave(self, ...))
	if running and not suppressDirty and isPremium and state.autoSave and activeCloudId and self.Profile == SHADOW_PROFILE then
		local payload = serializeCurrent(false)
		if type(payload) == 'string' and payload ~= lastObservedPayload then
			lastObservedPayload, dirty, lastChangedAt = payload, true, os.clock()
		end
	end
	return table.unpack(results, 1, results.n)
end

if type(originalUninject) == 'function' then
	mainapi.Uninject = function(self, ...)
		pcall(flushAutosave, true)
		running = false
		mainapi.Save = originalSave
		mainapi.Uninject = originalUninject
		return originalUninject(self, ...)
	end
end

if isPremium and mainapi.Profile == SHADOW_PROFILE and activeCloudId then
	lastObservedPayload = serializeCurrent(false)
elseif isPremium then
	activeCloudId, state.activeCloudId = nil, nil
end

applyMode()
if isPremium and mode == 'Cloud' then task.spawn(fetchCloudList) end

task.spawn(function()
	local lastCopySync = 0
	while running do
		task.wait(5)
		if not running then break end
		pcall(flushAutosave, false)
		local now = os.clock()
		if now - lastCopySync >= COPY_SYNC_INTERVAL then
			lastCopySync = now
			for key, record in state.localSync do
				if type(record) == 'table' and record.enabled == true and tostring(record.placeId) == tostring(mainapi.Place) then
					task.spawn(syncLocalCopy, key, record)
				end
			end
		end
	end
end)
